/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PetShop.PetShop;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
//import net.proteanit.sql.DbUtils;


/**
 *
 * @author jites
 */
public class AddPet extends javax.swing.JFrame {

    /**
     * Creates new form AddPet
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    
    public AddPet() {
        super("Pet Page");
        initComponents();
        setSize(1100,500);
        
    }
    public AddPet(int id){
        initComponents();
        userIDLabel.setText(Integer.toString(id));
        userIDLabel.setEditable(false);
        priceField.setEditable(false);
        totalField.setEditable(false);
        conn = DatabaseConnection.connection();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        categorySelector = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        subCategorySelector = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        quantityField = new javax.swing.JComboBox<>();
        idLabel = new javax.swing.JLabel();
        userIDLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 102, 102));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("About");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Logout");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton4)
                        .addComponent(jButton3)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        add.setBackground(new java.awt.Color(255, 102, 102));
        add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        categorySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item", "Cat", "Dog", "Birds", "Squirrels" }));
        categorySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorySelectorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Price");

        subCategorySelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        subCategorySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCategorySelectorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Category");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Sub Category");

        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total");

        totalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFieldActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        quantityField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Quantity", "1", "2", "3", "4", "5" }));
        quantityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityFieldActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLabel.setText("UserID :");

        userIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userIDLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(categorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(add))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subCategorySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(845, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginPage object = new LoginPage();
        object.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        About object = new About();
        object.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if(totalField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Select Quantity First");
        }else{
            try{
            stmt = conn.createStatement();
            String category = (String)categorySelector.getSelectedItem();
            String subCategory = (String)subCategorySelector.getSelectedItem();
            int price = Integer.parseInt(priceField.getText());
            String temp = (String)quantityField.getSelectedItem();
            int quantity = Integer.parseInt(temp);
            int totalPrice = Integer.parseInt(totalField.getText());
            String query = "INSERT INTO ADDPET(category, subCategory, price, quantity, totalPrice) VALUES('"+category+"', '"+subCategory+"', '"+price+"', '"+quantity+"', '"+totalPrice+"')";
            stmt.executeUpdate(query);
            
            
            //displaying on table
            
            query = "SELECT category, subCategory, price, quantity, totalprice FROM  ADDPET";
            rs = stmt.executeQuery(query);
            while(rs.next()){
                 jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            }
            JOptionPane.showMessageDialog(null, "Successfull Inserted Data");
            }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
        }
        
        
        
    }//GEN-LAST:event_addActionPerformed

    private void categorySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorySelectorActionPerformed
        // TODO add your handling code here:
        if(categorySelector.getSelectedIndex() != -1){
            if(categorySelector.getSelectedItem().equals("Cat")){
            subCategorySelector.removeAllItems();
            subCategorySelector.addItem("Abyssinian Cat");
            subCategorySelector.addItem("American Bobtail Cat Breed");
            subCategorySelector.addItem("American Curl Cat Breed");
            subCategorySelector.addItem("Birman Cat Breed");
            subCategorySelector.addItem("Chartreux Cat Breed");            
        }else if(categorySelector.getSelectedItem().equals("Dog")){
            subCategorySelector.removeAllItems();
            subCategorySelector.addItem("Affenpinscher");
            subCategorySelector.addItem("Akita");
            subCategorySelector.addItem("Alaskan Klee Kai");
            subCategorySelector.addItem("American Eskimo");
            subCategorySelector.addItem("American Bulldog");   
        }else if(categorySelector.getSelectedItem().equals("Birds")){
            subCategorySelector.removeAllItems();
            subCategorySelector.addItem("Gamebirds");
            subCategorySelector.addItem("Goldcrests and Kinglets");
            subCategorySelector.addItem("Falcons");
            subCategorySelector.addItem("Eagle");
            subCategorySelector.addItem("Toucans");   
        }else if(categorySelector.getSelectedItem().equals("Squirrels")){
            subCategorySelector.removeAllItems();
            subCategorySelector.addItem("Calabrian black squirrel");
            subCategorySelector.addItem("Bangs’s mountain squirrel");
            subCategorySelector.addItem("Tribe Marmotini");
            subCategorySelector.addItem("Tribe Protoxerini");
            subCategorySelector.addItem("Western gray squirrel");   
        }
        else{
            subCategorySelector.removeAllItems();
            subCategorySelector.addItem("Select Item");
            priceField.setText("0");
        }
        }
        
    }//GEN-LAST:event_categorySelectorActionPerformed

    private void subCategorySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCategorySelectorActionPerformed
        // TODO add your handling code here:
            if(subCategorySelector.getSelectedIndex() != -1){
                if(categorySelector.getSelectedItem().equals("Cat")){
            //Cat Selection
            priceField.setEditable(false);
            
            Object itemSelected = subCategorySelector.getSelectedItem();
            switch((String)itemSelected){
                case "Abyssinian Cat":
                    priceField.setText("20000");
                    break;
                case "American Bobtail Cat Breed":
                    priceField.setText("25000");
                    break;
                case "American Curl Cat Breed":
                    priceField.setText("30000");
                    break;
                case "Birman Cat Breed":
                    priceField.setText("35000");
                    break;
                case "Chartreux Cat Breed":
                    priceField.setText("40000");
                    break;
                default:
                    priceField.setText("0");
                    break;
            }
        }else if(categorySelector.getSelectedItem().equals("Dog")){
            //Dog Selection
             Object itemSelected = subCategorySelector.getSelectedItem();
            switch((String)itemSelected){
            case "Affenpinscher":
                priceField.setText("60000");
                break;
            case "Akita":
                priceField.setText("65000");
                break;
            case "Alaskan Klee Kai":
                priceField.setText("75000");
                break;
            case "American Eskimo":
                priceField.setText("80000");
                break;
            case "American Bulldog":
                priceField.setText("90000");
                break;
            default:
                    priceField.setText("0");
                    break;
        }
        }else if(categorySelector.getSelectedItem().equals("Birds")){
            //Birds Selection
             Object itemSelected = subCategorySelector.getSelectedItem();
            switch((String)itemSelected){
                case "Gamebirds":
                    priceField.setText("10000");
                    break;
                case "Goldcrests and Kinglets":
                    priceField.setText("15000");
                    break;
                case "Falcons":
                    priceField.setText("18000");
                    break;
                case "Eagle":
                    priceField.setText("80000");
                    break;
                case "Toucans":
                    priceField.setText("60000");
                    break;
                default:
                    priceField.setText("0");
                    break;
            }
        }else if(categorySelector.getSelectedItem().equals("Squirrels")){
            //Squirrels Selection
            Object itemSelected = subCategorySelector.getSelectedItem();
            switch((String)itemSelected){
                case "Calabrian black squirrel":
                    priceField.setText("7000");
                    break;
                case "Bangs’s mountain squirrel":
                    priceField.setText("10000");
                    break;
                case "Tribe Marmotini":
                    priceField.setText("18000");
                    break;
                case "Tribe Protoxerini":
                    priceField.setText("22000");
                    break;
                case "Western gray squirrel":
                    priceField.setText("25000");
                    break;
                default:
                    priceField.setText("");
                    break;
            }
        } 
            }
           
        
    }//GEN-LAST:event_subCategorySelectorActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        LoginPage object = new LoginPage();
        object.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void totalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void quantityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityFieldActionPerformed
        // TODO add your handling code here:
        if(quantityField.getSelectedItem().equals("Select Quantity")){
            totalField.setText("");
        }else{
                   String price = priceField.getText();
                   String quantity = (String)quantityField.getSelectedItem();
                   int total = Integer.parseInt(price) * Integer.parseInt(quantity);                   
                   totalField.setText(Integer.toString(total));
        }
    }//GEN-LAST:event_quantityFieldActionPerformed

    private void userIDLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDLabelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddPet().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> categorySelector;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField priceField;
    private javax.swing.JComboBox<String> quantityField;
    private javax.swing.JComboBox<String> subCategorySelector;
    private javax.swing.JTextField totalField;
    private javax.swing.JTextField userIDLabel;
    // End of variables declaration//GEN-END:variables
}
